version: "3"

services:
  app:
    #image: python:3.7
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=admin
      - DB_PASS=admin
    restart: always
    command: |
      sh -c "
          cd /app
          python manage.py initialize_buckets &&
          python manage.py makemigrations &&
          python manage.py migrate &&
          python manage.py runserver 0:8000
      "
    depends_on: 
      - db
  db: 
    image: postgres:13
    #ports:
      #- 5432:5432
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  minio:
    image: minio/minio
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    command: server /data
